require('lazy').setup({
  require 'custom.plugins.guess-indent',
  require 'custom.plugins.gitsigns',
  require 'custom.plugins.bufferline',
  require 'custom.plugins.lualine',
  require 'custom.plugins.nui',
  require 'custom.plugins.noice',
  require 'custom.plugins.smear-cursor',
  require 'custom.plugins.snacks',
  require 'custom.plugins.telescope',
  require 'custom.plugins.which-key',
  require 'custom.plugins.nvim-lspconfig',
  require 'custom.plugins.lazydev',
  require 'custom.plugins.nvim-treesitter',
  require 'custom.plugins.blink-cmp',
  require 'custom.plugins.conform',
  require 'custom.plugins.mini',
  require 'custom.plugins.todo-comments',
  require 'custom.themes.base16',
  require 'custom.themes.tokyonight',
}, {
  ui = {
    -- If you are using a Nerd Font: set icons to an empty table which will use the
    -- default lazy.nvim defined Nerd Font icons, otherwise define a unicode icons table
    icons = vim.g.have_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})
